// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOTMBLu8S6CTLoZYgcfZOKX6XCfQTaR3E',
    appId: '1:343722308746:web:6ce7660cb0c12a5b8ce973',
    messagingSenderId: '343722308746',
    projectId: 'game-7113b',
    authDomain: 'game-7113b.firebaseapp.com',
    storageBucket: 'game-7113b.appspot.com',
    measurementId: 'G-E25152VW3N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5Ava6-v4JVbHRJqPNbFidzXPd_fxi0Lc',
    appId: '1:343722308746:android:2c3c38489cfb41b98ce973',
    messagingSenderId: '343722308746',
    projectId: 'game-7113b',
    storageBucket: 'game-7113b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK1mGbm1XhmjRm2dJtsWcHmXIJldg5fms',
    appId: '1:343722308746:ios:2c964c932745b4288ce973',
    messagingSenderId: '343722308746',
    projectId: 'game-7113b',
    storageBucket: 'game-7113b.appspot.com',
    iosBundleId: 'com.example.game',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBK1mGbm1XhmjRm2dJtsWcHmXIJldg5fms',
    appId: '1:343722308746:ios:4e6c53e4d4624e298ce973',
    messagingSenderId: '343722308746',
    projectId: 'game-7113b',
    storageBucket: 'game-7113b.appspot.com',
    iosBundleId: 'com.example.game.RunnerTests',
  );
}
